packages:
    - ./package
    - ./test
    - ./bench
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

catalogs:
    dep:
        vitest: ^4.1.8
    dev:
        rolldown: 1.0.0
    peer:
        rolldown: ^1.0.0

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "ts-vista"
